name: Deploy to Surge

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
<<<<<<< HEAD
      with:
        node-version: '20'

=======
 with:
        node-version: '20'
>>>>>>> ea17dff95385ead61d04751cfa0e7696ab70b786
    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to Surge
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
<<<<<<< HEAD
     run: surge ./ https://hanselDevopsParcial.surge.sh
=======
      run: surge ./ https://hanselDevopsParcial.surge.sh
>>>>>>> ea17dff95385ead61d04751cfa0e7696ab70b786
